sudo: false
language: java
before_install:
  - jdk_switcher use openjdk6
  - sed -i "s|\[JDK6\]|$JAVA_HOME|g" etc/toolchains.xml
  - jdk_switcher use oraclejdk8
install:
  - ./mvnw install -Dinvoker.skip=true -DskipTests=true -B -V -t etc/toolchains.xml
script:
  - ./mvnw verify -B -t etc/toolchains.xml
after_success:
  - "[[ ${TRAVIS_PULL_REQUEST} == 'false' ]] && [[ ${TRAVIS_TAG} == '' ]] && ./mvnw deploy -Dinvoker.skip=true -DskipTests --settings etc/deploy-settings.xml -t etc/toolchains.xml"
  - ./mvnw verify coveralls:report -Dinvoker.skip=true -Prun-coverage -t etc/toolchains.xml
env:
  global:
    - secure: cttGV5bt0VuZZXHK0yo9rfszAjX67+pcRKMBjGuFEdr3v8uD55ho2qrXAtKEbG5x/g1atBXKD3HhBzK5Mb00XDkF93TQdX9veO6619xcVqQ7LdzPDIbbpX7lrS7vIaUaM77+hCtHFEKZs6+DVyeL93z0Vy7GiIAnRAnGomlmAwc=
    - secure: bjSYB4bs3FXRt9kPkPE3Qex00rckmnrKc1SoNiDXJ9ZHVjGRl3SXjcAUDQiTvmfliuUBMSRryCpjR4xqUywICEwD8tg9ubW7EbI8X12yxtGszJCoGQYTSlVc/bVgM+qaT/KxLvoCI3PTsPgEI/DsSIjmM4uVqzStgcgb02qZWE8=
